name: Build and Release

on:
  workflow_dispatch:
    inputs:
      level:
        options:
          - major
          - minor
        type: choice
        default: minor
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Bump Version
    outputs:
      version: ${{ steps.calver.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cal Ver
        uses: speechifyinc/calver-action@v1.20230308.0
        id: calver
        with:
          level: ${{ github.event.inputs.level }}
          token: ${{ github.token }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.calver.outputs.version }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer Dependencies
        uses: php-actions/composer@v6

      - name: Compile
        uses: php-actions/composer@v6
        with:
          command: run compile

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: urchin.phar
          tag_name: ${{ needs.bump-version.outputs.version }}
